/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:47605e25-e019-4218-bc7e-3c4a71e5ebf5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_kSYGi5oWv",
    "aws_user_pools_web_client_id": "40v045lo8sh4rs9oknh27qspv1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "reactuie04adec577c94c6f8c456c06d5c3f1a2213445-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
